### ISSUE TITLE
Add more configuration options to Effect system

### ISSUE THREAD

**Issue by sh0ckR6** [sh0ckR6/MineEffect#26]
The effect system as it currently stands feels a little static. There's not really much room for customization, and I think some more configuration options would be beneficial.

New proposed configuration options:
- Whitelist/Blacklist certain potion effects
  - If a whitelist is defined, all other effects will be implicitly blacklisted.
  - If a blacklist is defined, all other effects will be implicitly whitelisted.
  - There cannot be both a blacklist and whitelist.
- Individual settings for each potion effect
  - Any setting not explicitly defined will use defaults
- Option to override the failsafes added for the Wither and Instant Damage effects
  - These were implemented so the player couldn't instantly die to these effects

Example of how this could work:
```yaml
effects:
  allowed:
    - instant_health:
        amplifier:
          max: 15
          min: 5
        duration:
          max: 60
          min: 1
    - "speed"
  denied:
    - "wither"
    - bad_omen:
        amplifier:
          max: 2
  # Note: "allowed" and "denied" cannot be defined at the same time and are only both here for demonstration
  # Potentially send an error message to the user when loading configuration stating that both "allowed" and "denied" are both defined
```
